sudo: false
language: python
env:
  global:
    - NEWEST_PYTHON=2.7
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install pytest
script:
  - py.test
after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install python-coveralls && coveralls
    fi
